site_name: Basic CRUD lambda API
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
            - sys.path.append("infra")

nav:
    - Home: readme.md
    - Config: dotenv.md
    - Deploy: deploy.md
    - API: api.md
    - Layer: layers.md
    - Makefile: makefile.md
    - Docs: docs.md
    - Code Reference:
      - Models: refs/models.md
      - Events: refs/events.md
      - Api: refs/api.md
      - CDK: refs/infra.md
