site_name:  lambda-dynamo-cdk api with powertools
repo_name: rbogle/crud_api_lambda_powertools
repo_url: https://github.com/rbogle/crud_api_lambda_powertools

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
            - sys.path.append("infra")

nav:
    - Home: index.md
    - Config: dotenv.md
    - Deploy: deploy.md
    - API: api.md
    - Layer: layers.md
    - Makefile: makefile.md
    - Docs: docs.md
    - Code Reference:
      - Models: refs/models.md
      - Events: refs/events.md
      - Api: refs/api.md
      - CDK: refs/infra.md
